[workspace]
channels = ["conda-forge"]
name = "prefect3 test"
platforms = ["linux-64"]

[dependencies]
prefect = "3.*"
python = "<3.14"
tiled = ">=0.2.3"
prefect-docker = "*"
bluesky-tiled-plugins = ">=2"
nexusformat = "*"
